### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by sergeScherbakov** [ReanGD/LearningEnglish#89]
версия 0.4 работает хорошо, а последняя вылетает при запуске:

E:\artists\vendors\python\win32>Traceback (most recent call last):
  File "e:\Dropbox\English\EnglishWords\main.py", line 43, in <module>
    run_main()
  File "e:\Dropbox\English\EnglishWords\main.py", line 33, in run_main
    src.app.App()
  File "e:\Dropbox\English\EnglishWords\src\app.py", line 20, in **init**
    self.new_lesson()
  File "e:\Dropbox\English\EnglishWords\src\app.py", line 26, in new_lesson
    self.lesson = lesson.Lesson(self.cfg)
  File "e:\Dropbox\English\EnglishWords\src\lesson.py", line 62, in **init**
    self.dict.reload_dict(cfg["path_to_dict"])
  File "e:\Dropbox\English\EnglishWords\src\dictionary.py", line 118, in reload_
dict
    self.reload_dict_from_json(self.load_dict_as_json(path))
  File "e:\Dropbox\English\EnglishWords\src\dictionary.py", line 115, in load_di
ct_as_json
    return json.load(codecs.open(path, "rt", "utf-8"))
  File "E:\artists\vendors\python\win32\lib\codecs.py", line 881, in open
    file = **builtin**.open(filename, mode, buffering)
ValueError: Invalid mode ('rtb')

Пробовал на чистом питоне 2.7.3 и Python 2.7.4 Anaconda 1.5.0 (64-bit)
Версия чистая, с дефолтным словарем.

**Comment by ReanGD** [comment]
Да, это в последних релизах python 2.x api работы с файлами немного поменяли. Лень было смотреть, но раз уж кто-то кроме меня наткнулся, придется править )

**Comment by ReanGD** [comment]
Поправил в ветке master, если все в порядке, можно закрывать

**Comment by sergeScherbakov** [comment]
да, всё заработало, спасибо большое!

**Comment by alexeydidenko** [comment]
Спасибо Вам за отличнейшую программу-для меня альтернативы просто нет: ничего лишнего-лишь необходимый функционал. Но все же есть вопрос (прошу прощения, если уже поднимался). Программа гораздо чаще предлагает учить направление перевода слов En-Ru, а хотелось бы равномерное распределение по обоим направлениям. Это нормальный порядок вещей?

**Comment by ReanGD** [comment]
Спасибо за отзыв. Мне кажется это у вас субъективное, т.к. выбирается тип перевода абсолютно случайно: https://github.com/ReanGD/LearningEnglish/blob/master/src/lesson.py#L53 может конечно в библиотеке python ошибка, но маловероятно.
